language: go
go:
- 1.10.x
- 1.11.x
- tip
matrix:
  allow_failures:
  - go: tip
services:
- docker
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
    repo: shift/continent8_exporter
env:
  global:
  - secure: DMvr+zAxJnYM4XOV8pL5AIcNquN1Ob8yTVRd2HtWORA+Sl/nyWgPgKS+FmQMBcDq4q36p6J5Us/bK5gqrfW6sWgE119Dji9dKE1i+oWeBFG0DT8/vFMJpxbpZ+seMSnyPAB5IVXWNKxqjbb/2tjHIJd/CCABx5Ly7gJcdLI5ufe1H0b1xjFBSe5Yizar6aNS3xnBFj1E7wng27lbvVPZDjHr3/68J7jlXfnVIlFrdCVij++d+CshwivC6wQ0N7tCEvL/UfAOBNchL4ADo9+rkbMfXwNEEbg6BRhOFj9w8Ay/UXUfoH4qx6rxf60M10sVtAqN05def32mQTrFFMDA0DmtsIqUm1Nh4XTlCjc0k5Nr4PzjqJzHpMmwZ1UDLZA9KrefecNyZ3YIfQALdUikLMrJxv74/o3FniLYr52BGLaCoAxmtrhWCIDWzSbTa83tB1K8ZaVUFUIPWP/rnN5KYAWtpIbUJHpqI4c5Jwbm5S+gtqMSoONx+j5UxW7mHdfmgIElnXK8eRjuJJyAjMnIWZ/LiRnIYVhGpRTTmOnerAK6EH3OxqXzI8iyMAhPIN+yvNntCjf0yFXYEEvR5zXLy2tBQQLOPv8hFeyZ/+ednhl7hnyLEtdEc+HzqivXT/KhgWe0gMKEc2mWFriDGI8RNacKIfFjmRO1Ul8oxSgRmcE=
  - secure: q4qnio57sF5bq7nc0nqBDrMzZlv0lTNCm6MauOFQFMjNLzrRPsTLBc+y9BAPq/OzO3um1rYKnLXqWZqpX9J3+cLvRZIvDgMw1Jg7RjouPMdko/B1FqMVDcY05ciL55+81QZOZeUiQgriFKC2CoLgIfx7I/C1AbMR/nrI9E7WCtgYz0EZHbMSnruBcvXcwjvdoXi8H5EkyVJMOsQte9HORrozbzOxGl9SPCOVYW/kQYhhQhYfPvAGK8PQAamSNikgISWGY3SBpFSc4wpK8t1p0mIefGoDU/RueoNyUc91UaLTBOACLRHsAHaXgj3vTXatBZNBUkrZh4eQeGsxdFcSCPRB4i64bRS00Th6s3vvK88/T7yPapkTVd0pdUTkS2P72gZBK6mszrdKVQ1uIDl54vmMVJCI62TygRF0YY1OpAoILZDaPK9GnyodZLPhlqPx8U982L3QA6uS8K28l5bv4wYjuncgrmkIGtF0SmVbH0y/GAwQ+uX4trSFcESdMgQmIB9bAUZXMzSeLQLMzdjCSeS9oRZWh2GwR0lv9xxF/d4E2N15xnTOtIyfIB9aKQ3OQhSRJmf4JMQq6EN7M5bhWhE/+Ef3oivIir3OWXN5rtURy4wPLCekGTiSOwGrPi9CvEo/U/Pk/YlSSRCWeth52G9tJhmvQ5DO/0+4G7WAMqc=
  - secure: bimyIthPkTAOvaD/NV4HmBrZAZj/r7mAg9ZAtkRWuIRmfnVmqye1M4HyOUTJHaG/av4qFlEEn5sF2ZC817CD8T+9NgnvBTQuCc7rmHctWSfL9ozZiekPQyGQ+Bn24bz/Sybc73mCpg1JeOF8cz6QgLuxNuGWRPiYFJxlB2+oXYhiFaBAqt6A+dl/Wvt42IUy6Ot0IWBspZJABqhqz0lJamft24H2VcUfv/MRQ4gevulhGzf3FKXnwM8UN3qBACsV/ljmMtZbZlIwMpqygGD1TAy7bQnD0NG1md+yiSJK9B60LxLqVAx+Noe4WYlKBoI6DIfpoM8Qqv4RrzWo5zAAq3ywJbvFutbpJ4d72GlxxcPsBXs1QA5DCOEhDmAlZihIQJnNNDHiOAJ2cmZcHxq4975yFZ6/J+xseEVSR3ghHwiJ2vtS4rFgxZd2GYPFQrNfZ4zAzDS3ay3lY7ailYP1ci2LeundBl9TBjr4eSnOxp13Pu/sJdFqpl/TAGgamtEntxX0TjUbCdnd/Z5ZTmPbvL6vIz+jR34XnkkKdJUzn6MZFk/p0z+L8sdQWS6+M/TNLklMu4tNvrTRFoh5is6O1U7H22pgJ8MZf+/FC5QqcD/sbmWtJHG7F+2y9GAY+PQxhj9VZSvG9zXriZmrywPrz70fmHkS8xvWRJkZqfleQxM=
